
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Taanveer Ahmeed
 */
public class SendMail extends javax.swing.JPanel {

    /**
     * Creates new form SendMail
     */
    public SendMail(Gui g) {
        
         initComponents();
         
        
         try {
               courseID.removeAllItems();
               courseID.addItem("ID-Name-ClassID");
               //studentList.addItem("Student ID");
               g.rs = g.st.executeQuery("select * from course where teacherId = '" +g.loggedInTeacher+"'");
               while (g.rs.next()){
                   
                  courseID.addItem(g.rs.getString("courseID")+"-"+g.rs.getString("courseName")+"-"+g.rs.getString("classID"));
                               
                  }
               
              } catch (SQLException ex) {
                                  JOptionPane.showMessageDialog(null, ex);
                                  
              }
        
         
         send.addActionListener(
                 new ActionListener (){
                     public void actionPerformed (ActionEvent ev){
                         
                         if (courseID.getSelectedIndex() == 0){
                             
                             JOptionPane.showMessageDialog(null, "Please Select Course");
                         
                         }
                         
                         else{
                             
                             String mailContent = content.getText();
                             //System.out.print(mailContent);
                             String [] coursesName = courseID.getSelectedItem().toString().split("-");
                             
                             DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                            Calendar cal = Calendar.getInstance();
                            System.out.println(dateFormat.format(cal.getTime()));
                          
                             
                             String query = "insert into mails values ('"+g.loggedInTeacher+"','"+coursesName[0]+"','"+content.getText()+"','"+dateFormat.format(cal.getTime())+"')";
                             //System.out.println (query);
                            
                            try {
                                
                                g.st.executeUpdate (query);
                                JOptionPane.showMessageDialog(null,"Success");
                            
                            }catch (Exception ex){
                            
                                JOptionPane.showMessageDialog(null, ex);
                            }
                             
                         
                         }
                     
                     }
                 }
         
         );
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        courseID = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        content.setColumns(20);
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        send.setText("Send");

        jLabel1.setText("Couses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(send)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(courseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(send)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea content;
    public javax.swing.JComboBox<String> courseID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
