
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Taanveer Ahmeed
 */
public class StudentInbox extends javax.swing.JPanel {

    /**
     * Creates new form StudentInbox
     */
    public StudentInbox(Gui g) {
        initComponents();
         try {
                courses.removeAllItems();
                courses.addItem("Course ID-Course Name-Class ID");
                String query = " SELECT * FROM `course` WHERE classID = (select classID from studentrelationtoclass where studentID = '" +g.loggedInStudent +"')";
                g.rs = g.st.executeQuery(query);
                while (g.rs.next()){
                    courses.addItem(g.rs.getString("courseID") + "-" + g.rs.getString("courseName")+"-"+g.rs.getString("classID"));
                                      
                                      
                    }
            } catch (SQLException ex) {
                                  JOptionPane.showMessageDialog(null, ex);
                    }
         
         courses.addItemListener(
                 new ItemListener (){
                     public void itemStateChanged (ItemEvent ev){
                         
                         
                        if (ev.getStateChange () == ItemEvent.SELECTED)
                        {
                         
                         if (courses.getSelectedIndex() == 0){
                             
                             
                             
                             JOptionPane.showMessageDialog(null, "Please select a Course");
                         
                         }
                         
                         else{
                             
                             
                                    output.setText("");
                                    String [] courseDetails = courses.getSelectedItem().toString().split("-");
                                    String query = "select * from mails where receiver = '" +courseDetails[0]+"'";
                                    //System.out.println (query);
                                    try {
                                    
                                        g.rs = g.st.executeQuery(query);
                                        while (g.rs.next()){
                                            
                                            output.setText(g.rs.getString("mailContent")+"     Sent Time :"+g.rs.getString("sentTime"));
                                        
                                        }
                                    }catch (Exception ex){
                                    
                                    }
                             }
                         
                         }
                     
                     }
                 
                 }
         
         );
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courses = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();

        jLabel1.setText("Courses");

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> courses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
